const mongoose = require('mongoose');

/**
 * Diagnosis Schema - Stores AI-generated and veterinarian diagnoses
 */
const diagnosisSchema = new mongoose.Schema(
  {
    cow: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Cow',
      required: true,
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    // Source of diagnosis
    source: {
      type: String,
      enum: ['ai', 'veterinarian', 'manual'],
      default: 'manual',
    },
    // Diagnosis details
    condition: {
      type: String,
      required: [true, 'Please add a condition/diagnosis'],
      trim: true,
    },
    category: {
      type: String,
      enum: [
        'respiratory',
        'digestive',
        'reproductive',
        'metabolic',
        'infectious',
        'parasitic',
        'injury',
        'nutritional',
        'other',
      ],
      default: 'other',
    },
    severity: {
      type: String,
      enum: ['low', 'medium', 'high', 'critical'],
      default: 'medium',
    },
    // Symptoms that led to diagnosis
    symptoms: {
      type: String,
      trim: true,
    },
    // Confidence score for AI diagnoses (0-100)
    confidenceScore: {
      type: Number,
      min: 0,
      max: 100,
      default: null,
    },
    // Treatment plan
    treatment: {
      type: String,
      trim: true,
    },
    medications: [
      {
        name: { type: String, trim: true },
        dosage: { type: String, trim: true },
        frequency: { type: String, trim: true },
        duration: { type: String, trim: true },
      },
    ],
    // Status tracking
    status: {
      type: String,
      enum: ['suspected', 'confirmed', 'treated', 'resolved', 'chronic'],
      default: 'suspected',
    },
    resolvedDate: {
      type: Date,
    },
    // Link to health record if created from one
    healthRecord: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'HealthRecord',
    },
    // Additional Gemini-powered fields
    likelyCauses: {
      type: String,
      trim: true,
    },
    preventionTips: {
      type: String,
      trim: true,
    },
    requiresVetAttention: {
      type: Boolean,
      default: false,
    },
    disclaimer: {
      type: String,
      default: 'This is an AI-assisted assessment generated by Google Gemini. It is not a confirmed veterinary diagnosis. Always consult a licensed veterinarian.',
    },
    // Additional notes
    notes: {
      type: String,
      trim: true,
    },
    // For image-based detection (future feature)
    imageAnalysis: {
      imageUrl: { type: String },
      findings: { type: String },
      detectedConditions: [{ type: String }],
    },
    // AI health score (0-100)
    healthScore: {
      type: Number,
      min: 0,
      max: 100,
      default: null,
    },
    // Raw Gemini response for audit
    rawResponse: {
      type: String,
      select: false,
    },
    // Number of conditions analyzed
    conditionsCount: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true,
  }
);

// Index for efficient queries
diagnosisSchema.index({ cow: 1, createdAt: -1 });
diagnosisSchema.index({ user: 1, status: 1 });

module.exports = mongoose.model('Diagnosis', diagnosisSchema);